### PR TITLE
Latest upstream

### PR DESCRIPTION
**Pull request by iggy**
I'll have to force push this to master if you approve it as I added tablespace support to our copy in a different way initially.

This is what we've been running in dev for a while now merged upstream. I've also tested it a fair amount post merge.

### CODE REVIEW

**Comment by ocsbrandon** [comment]
have we tested in QA?

**Comment by iggy** [comment]
I can't until I get this merged. Hopefully once I get the pygit2 stuff working (next month?) we can use git branches like they were meant to be used. Until then though, I need to merge, then test in QA, then move to prod.

**Comment by iggy** [comment]
I have tested in development though. Thankfully the DB server is fairly self contained.

**Comment by ocsbrandon** [comment]
Hmmmm. might be best to wait until after we ship then

On Mon, Apr 27, 2015 at 10:20 AM, Brian Jackson <notifications@github.com>
wrote:

> I can't until I get this merged. Hopefully once I get the pygit2 stuff
> working (next month?) we can use git branches like they were meant to be
> used. Until then though, I need to merge, then test in QA, then move to
> prod.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OnCenterSoftware/postgres-formula/pull/1#issuecomment-96701840>
> .
>



-- 

Sincerely,

*Brandon Davis*
*Chief Software Architect*

On Center Software, Inc.

*P:* 281.210.0182
*F:* 281.xxx.xxxx
*W:* *http://www.oncenter.com <http://www.oncenter.com/>*

**Comment by iggy** [comment]
Okay, then don't run highstate in production (on *db*).

**Comment by ocsbrandon** [comment]
oh, hmmm... maybe we should try it in QA then.

On Mon, Apr 27, 2015 at 10:27 AM, Brian Jackson <notifications@github.com>
wrote:

> Okay, then don't run highstate in production (on *db*).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OnCenterSoftware/postgres-formula/pull/1#issuecomment-96708628>
> .
>



-- 

Sincerely,

*Brandon Davis*
*Chief Software Architect*

On Center Software, Inc.

*P:* 281.210.0182
*F:* 281.xxx.xxxx
*W:* *http://www.oncenter.com <http://www.oncenter.com/>*

**Comment by ocsbrandon** [comment]
looks good.

**Pull request closed without merging**
